In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df = df.head(200)

print("Rows and Columns:", df.shape)
df.head()

Rows and Columns: (200, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.to_csv("titanic_200.csv", index=False)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             41
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          160
Embarked         1
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_csv("titanic_200.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'titanic_200.csv'

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

# Keep exactly 200 rows
df = df.head(200)

print("Rows and Columns:", df.shape)

Rows and Columns: (200, 12)

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

print("Missing Age values:", df['Age'].isnull().sum())

Missing Age values: 0

In [ ]:
df['Cabin'] = df['Cabin'].fillna('Unknown')

print("Missing Cabin values:", df['Cabin'].isnull().sum())

Missing Cabin values: 0

In [ ]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

print("Missing Embarked values:", df['Embarked'].isnull().sum())

Missing Embarked values: 0

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
print("Number of duplicate rows:", df.duplicated().sum())

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_csv("titanic_200.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'titanic_200.csv'

In [ ]:
import pandas as pd

df = pd.read_csv("titanic_200.csv")

print(df.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'titanic_200.csv'

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

# Keep only 200 rows
df = df.head(200)

# Step 1: Handle missing values
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Cabin'] = df['Cabin'].fillna('Unknown')
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

print("Rows and Columns:", df.shape)

Rows and Columns: (200, 12)

In [ ]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
print("Data types checked successfully")
print(df.dtypes)

Data types checked successfully
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,100.500000,0.345000,2.420000,28.017799,0.680000,0.435000,27.518915
std,57.879185,0.476561,0.797987,13.628812,1.298472,0.871535,36.701640
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,0.000000
25%,50.750000,0.000000,2.000000,20.750000,0.000000,0.000000,8.050000
50%,100.500000,0.000000,3.000000,28.017799,0.000000,0.000000,14.772900
75%,150.250000,1.000000,3.000000,33.250000,1.000000,1.000000,30.227050
max,200.000000,1.000000,3.000000,71.000000,8.000000,5.000000,263.000000

In [ ]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

Q1: 8.05
Q3: 30.22705
IQR: 22.177049999999998
Lower Limit: -25.215574999999998
Upper Limit: 63.492625

In [ ]:
outliers = df[(df['Fare'] < lower_limit) | (df['Fare'] > upper_limit)]

print("Number of Fare outliers:", len(outliers))

Number of Fare outliers: 18

In [ ]:
df = df[(df['Fare'] >= lower_limit) & (df['Fare'] <= upper_limit)]

print("Rows after removing outliers:", len(df))

Rows after removing outliers: 182

In [ ]:
print(df['Fare'].max())

63.3583

In [ ]:
df['Name'] = df['Name'].str.strip()

print(df['Name'].head())

0                         Braund, Mr. Owen Harris
2                          Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                        Allen, Mr. William Henry
5                                Moran, Mr. James
Name: Name, dtype: object

In [ ]:
df['Sex'] = df['Sex'].str.strip().str.lower()

print(df['Sex'].unique())

['male' 'female']

In [ ]:
df['Embarked'] = df['Embarked'].str.strip().str.upper()

print(df['Embarked'].unique())

['S' 'Q' 'C']

In [ ]:
df_encoded = pd.get_dummies(df, columns=['Sex', 'Embarked'])

print(df_encoded.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3

                                           Name        Age  SibSp  Parch  \
0                       Braund, Mr. Owen Harris  22.000000      1      0
2                        Heikkinen, Miss. Laina  26.000000      0      0
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.000000      1      0
4                      Allen, Mr. William Henry  35.000000      0      0
5                              Moran, Mr. James  28.017799      0      0

             Ticket     Fare    Cabin  Sex_female  Sex_male  Embarked_C  \
0         A/5 21171   7.2500  Unknown       False      True       False
2  STON/O2. 3101282   7.9250  Unknown        True     False       False
3            113803  53.1000     C123        True     False       False
4            373450   8.0500  Unknown       False      True       False
5            330877   8.4583  Unknown       False      True       False

   Embarked_Q  Embarked_S
0       False        True
2       False        True
3       False        True
4       False        True
5        True       False

In [ ]:
print(df_encoded.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Sex_female', 'Sex_male', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 182 entries, 0 to 199
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  182 non-null    int64
 1   Survived     182 non-null    int64
 2   Pclass       182 non-null    int64
 3   Name         182 non-null    object
 4   Sex          182 non-null    object
 5   Age          182 non-null    float64
 6   SibSp        182 non-null    int64
 7   Parch        182 non-null    int64
 8   Ticket       182 non-null    object
 9   Fare         182 non-null    float64
 10  Cabin        182 non-null    object
 11  Embarked     182 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 63.1 KB

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 182 entries, 0 to 199
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  182 non-null    int64
 1   Survived     182 non-null    int64
 2   Pclass       182 non-null    int64
 3   Name         182 non-null    object
 4   Sex          182 non-null    object
 5   Age          182 non-null    float64
 6   SibSp        182 non-null    int64
 7   Parch        182 non-null    int64
 8   Ticket       182 non-null    object
 9   Fare         182 non-null    float64
 10  Cabin        182 non-null    object
 11  Embarked     182 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 63.1 KB

In [ ]:
df.to_csv("cleaned_titanic_200.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
print(df.shape)

(182, 12)

In [ ]:
df_encoded.to_csv("cleaned_titanic_encoded.csv", index=False)

print("Encoded cleaned dataset saved successfully!")

Encoded cleaned dataset saved successfully!